/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abririmagen;

import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;

/**
 *
 * @author DouglasRojas
 */
public class OperacionPuntual extends javax.swing.JFrame {

    Operaciones a1=new Operaciones();
    Operaciones a2=new Operaciones();
    public OperacionPuntual() {
        initComponents();
        this.setTitle("Operaciones Puntuales");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOp = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        suma = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        producto = new javax.swing.JButton();
        max = new javax.swing.JButton();
        min = new javax.swing.JButton();
        and = new javax.swing.JButton();
        or = new javax.swing.JButton();
        xor = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jToolBar1.setRollover(true);

        suma.setText("Suma");
        suma.setFocusable(false);
        suma.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        suma.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaActionPerformed(evt);
            }
        });
        jToolBar1.add(suma);

        resta.setText("Resta");
        resta.setFocusable(false);
        resta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        resta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });
        jToolBar1.add(resta);

        producto.setText("Producto");
        producto.setFocusable(false);
        producto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        producto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoActionPerformed(evt);
            }
        });
        jToolBar1.add(producto);

        max.setText("Max");
        max.setFocusable(false);
        max.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        max.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxActionPerformed(evt);
            }
        });
        jToolBar1.add(max);

        min.setText("Min");
        min.setFocusable(false);
        min.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        min.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        min.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minActionPerformed(evt);
            }
        });
        jToolBar1.add(min);

        and.setText("And");
        and.setFocusable(false);
        and.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        and.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        and.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andActionPerformed(evt);
            }
        });
        jToolBar1.add(and);

        or.setText("Or");
        or.setFocusable(false);
        or.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        or.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        or.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orActionPerformed(evt);
            }
        });
        jToolBar1.add(or);

        xor.setText("Xor");
        xor.setFocusable(false);
        xor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        xor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xorActionPerformed(evt);
            }
        });
        jToolBar1.add(xor);

        jButton1.setText("Abrir imagen 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Abrir imagen 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         BufferedImage imagen=a1.abrirImagen();
        //ImageIcon ico=new ImageIcon(imagen);
        System.out.println("alto:"+imagen.getHeight());
         System.out.println("ancho:"+imagen.getWidth());
         //agregamos imagen al panel
        ventana nueva=new ventana(imagen);
        jPanel1.add(nueva);
        nueva.setLocation(10, 10);
        nueva.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         BufferedImage imagen2=a2.abrirImagen();
        ImageIcon ico=new ImageIcon(imagen2);
        
        System.out.println("alto:"+imagen2.getHeight());
         System.out.println("ancho:"+imagen2.getWidth());
         //agregamos imagen a jlabel
        ventana nueva=new ventana(imagen2);
        jPanel1.add(nueva);
        nueva.setLocation(100, 10);
        nueva.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaActionPerformed
        // TODO add your handling code here:
        BufferedImage salida=null;
        salida=a1.suma(a2.getImagen());
         ventana nueva=new ventana(salida);
        jPanel1.add(nueva);
        nueva.setLocation(400, 10);
        nueva.show();
    }//GEN-LAST:event_sumaActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        // TODO add your handling code here:
         BufferedImage salida=null;
        salida=a1.resta(a2.getImagen());
         ventana nueva=new ventana(salida);
        jPanel1.add(nueva);
        nueva.setLocation(400, 10);
        nueva.show();
    }//GEN-LAST:event_restaActionPerformed

    private void productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoActionPerformed
        // TODO add your handling code here:
         BufferedImage salida=null;
        salida=a1.multiplicacion(a2.getImagen());
         ventana nueva=new ventana(salida);
        jPanel1.add(nueva);
        nueva.setLocation(400, 10);
        nueva.show();
    }//GEN-LAST:event_productoActionPerformed

    private void maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxActionPerformed
        // TODO add your handling code here:
         BufferedImage salida=null;
        salida=a1.maximo(a2.getImagen());
         ventana nueva=new ventana(salida);
        jPanel1.add(nueva);
        nueva.setLocation(400, 10);
        nueva.show();
    }//GEN-LAST:event_maxActionPerformed

    private void minActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minActionPerformed
        // TODO add your handling code here:
         BufferedImage salida=null;
        salida=a1.minimo(a2.getImagen());
         ventana nueva=new ventana(salida);
        jPanel1.add(nueva);
        nueva.setLocation(400, 10);
        nueva.show();
    }//GEN-LAST:event_minActionPerformed

    private void andActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andActionPerformed
        // TODO add your handling code here:
         BufferedImage salida=null;
        salida=a1.and(a2.getImagen());
         ventana nueva=new ventana(salida);
        jPanel1.add(nueva);
        nueva.setLocation(400, 10);
        nueva.show();
    }//GEN-LAST:event_andActionPerformed

    private void orActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orActionPerformed
        // TODO add your handling code here:
         BufferedImage salida=null;
        salida=a1.or(a2.getImagen());
         ventana nueva=new ventana(salida);
        jPanel1.add(nueva);
        nueva.setLocation(400, 10);
        nueva.show();
    }//GEN-LAST:event_orActionPerformed

    private void xorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xorActionPerformed
        // TODO add your handling code here:
         BufferedImage salida=null;
        salida=a1.xor(a2.getImagen());
         ventana nueva=new ventana(salida);
        jPanel1.add(nueva);
        nueva.setLocation(400, 10);
        nueva.show();
    }//GEN-LAST:event_xorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacionPuntual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacionPuntual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacionPuntual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionPuntual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OperacionPuntual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton and;
    private javax.swing.ButtonGroup grupoOp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton max;
    private javax.swing.JButton min;
    private javax.swing.JButton or;
    private javax.swing.JButton producto;
    private javax.swing.JButton resta;
    private javax.swing.JButton suma;
    private javax.swing.JButton xor;
    // End of variables declaration//GEN-END:variables
}
